// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPLzmCg_ilPT42x7ZtaUbOVKfbf-plAvI',
    appId: '1:257206606371:web:ef4c851e1647ecb1a4af96',
    messagingSenderId: '257206606371',
    projectId: 'virtualcityguess',
    authDomain: 'virtualcityguess.firebaseapp.com',
    storageBucket: 'virtualcityguess.appspot.com',
    measurementId: 'G-BCFZYNWM1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsnBJU8ndzaUc3WAhuYhdjUpoaPmT5pbI',
    appId: '1:257206606371:android:c9e5e141cca3dd82a4af96',
    messagingSenderId: '257206606371',
    projectId: 'virtualcityguess',
    storageBucket: 'virtualcityguess.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6UT34Nlk2zbhzUepvfzTPUqSGZ8k_Qzc',
    appId: '1:257206606371:ios:531bb44279ca7128a4af96',
    messagingSenderId: '257206606371',
    projectId: 'virtualcityguess',
    storageBucket: 'virtualcityguess.appspot.com',
    iosBundleId: 'com.example.virtualcityguess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6UT34Nlk2zbhzUepvfzTPUqSGZ8k_Qzc',
    appId: '1:257206606371:ios:531bb44279ca7128a4af96',
    messagingSenderId: '257206606371',
    projectId: 'virtualcityguess',
    storageBucket: 'virtualcityguess.appspot.com',
    iosBundleId: 'com.example.virtualcityguess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPLzmCg_ilPT42x7ZtaUbOVKfbf-plAvI',
    appId: '1:257206606371:web:85525e0a6b0ed5eea4af96',
    messagingSenderId: '257206606371',
    projectId: 'virtualcityguess',
    authDomain: 'virtualcityguess.firebaseapp.com',
    storageBucket: 'virtualcityguess.appspot.com',
    measurementId: 'G-EYZEHFYF1C',
  );
}
